service: ${self:custom.servicename}

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  apiGateway:
    apiKeys:
      - ${self:custom.apikeyname}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.tablename}
        - Effect: Allow
          Action: "s3:*"
          Resource: arn:aws:s3:::${self:custom.bucketname}/*
  environment:
    BUCKET_NAME: ${self:custom.bucketname}
    REGION: ${aws:region}
    SECRET: ${self:custom.secretname}
    TABLE_NAME: ${self:custom.tablename}

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-apigateway-service-proxy
  - serverless-lift

package:
  individually: true
  patterns:
    - "!**"

functions:
  custom-authorizer:
    handler: src/authorizer/handler.authorize
    package:
      patterns:
        - "src/authorizer/handler.js"
  get-users:
    handler: src/get-users/handler.getUsers
    package:
      patterns:
        - "src/get-users/handler.js"
    events:
      - http:
          path: users/{id}
          private: true
          method: GET
          request:
            parameters:
              paths:
                id: true
  create-user:
    handler: src/create-user/handler.createUser
    package:
      patterns:
        - "src/create-user/handler.js"
    events:
      - http:
          path: users
          authorizer:
            name: custom-authorizer
            resultTtlInSeconds: 15
          method: POST
          request:
            schemas:
              application/json: ${file(./src/schemas/user-schema.json)}
  update-user:
    handler: src/update-user/handler.updateUser
    package:
      patterns:
        - "src/update-user/handler.js"
    events:
      - http:
          path: users/{id}
          method: PATCH
          request:
            parameters:
              paths:
                id: true
            schemas:
              application/json: ${file(./src/schemas/user-schema.json)}
  delete-user:
    handler: src/delete-user/handler.deleteUser
    runtime: python3.11
    package:
      patterns:
        - "src/delete-user/handler.py"
    events:
      - http:
          path: users/{id}
          method: DELETE
          request:
            parameters:
              paths:
                id: true
  sing-url:
    handler: src/sing-url/handler.signedS3URL
    package:
      patterns:
        - "src/sing-url/handler.js"
    events:
      - http:
          path: signedurl
          method: GET
          request:
            parameters:
              querystrings:
                filename: true
  thumbnail-generator:
    handler: src/thumbnail/handler.thumbnailGenerator
    layers:
      - { Ref: BaseLambdaLayer }
    package:
      patterns:
        - "src/thumbnail/handler.js"
    events:
      - s3:
          bucket: ${self:custom.bucketname}
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: upload/

constructs:
  sqs-queu:
    type: queue
    batchSize: 1
    worker:
      handler: src/likeuser/handler.likeuser
      # reservedConcurrency: 1
      package:
        patterns:
          - "src/likeuser/handler.js"
    extensions:
      queue:
        Properties:
          QueueName: ${self:custom.queuename}

custom:
  servicename: demo-serverless-apigw-dynamodb
  tablename: ${self:custom.servicename}-${self:provider.stage}-table
  bucketname: ${self:custom.servicename}-${self:provider.stage}-bucket
  queuename: ${self:custom.servicename}-${self:provider.stage}-likequeue
  secretname: ${ssm:/${self:custom.servicename}/${self:provider.stage}}
  apikeyname: ${self:custom.servicename}-${self:provider.stage}-apikey
  serverless-dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
  apiGatewayServiceProxies:
    - sqs:
        path: /likeuser
        method: post
        queueName: ${self:custom.queuename}
        cors: true
        response:
          template:
            # `success` is used when the integration response is 200
            success: |-
              { "message": "accepted" }
             # `clientError` is used when the integration response is 400
            clientError: |-
              { "message": "there is an error in your request" }
             # `serverError` is used when the integration response is 500
            serverError: |-
              { "message": "there was an error handling your request" }

layers:
  base:
    name: thumbnail-generator-dependencies
    compatibleRuntimes:
      - nodejs18.x
    compatibleArchitectures:
      - x86_64
    package:
      artifact: layers/nodejs.zip

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tablename}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    S3Bucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: ${self:custom.bucketname}
        PublicAccessBlockConfiguration:
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
    S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action: "s3:GetObject"
              Resource: !Join
                - ""
                - - "arn:aws:s3:::"
                  - !Ref S3Bucket
                  - /*
